CREATE DATABASE battlechallenge;
USE battlechallenge;

CREATE TABLE users ( 
id_user INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
username VARCHAR(50) UNIQUE NOT NULL, 
email VARCHAR(255) UNIQUE NOT NULL , 
mdp VARCHAR (255) NOT NULL, 
points INT 
) ENGINE=INNODB; 

CREATE TABLE challenge ( 
id_challenge INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
titre VARCHAR (50) NOT NULL, 
contenu TEXT NOT NULL, 
difficulte ENUM ('EASY','MEDIUM','HARD') NOT NULL , 
points INT NOT NULL
) ENGINE=INNODB; 

CREATE TABLE submissions ( 
id_sub INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
user_sub INT UNSIGNED NOT NULL, 
sub TEXT NOT NULL, 
langage VARCHAR(20) DEFAULT 'javascript', 
id_challenge INT UNSIGNED NOT NULL, 
CONSTRAINT sub 
FOREIGN KEY (user_sub) 
REFERENCES users (id_user) 
ON DELETE CASCADE 
ON UPDATE RESTRICT, 
CONSTRAINT challenge_sub 
FOREIGN KEY (id_challenge) 
REFERENCES challenge (id_challenge) 
ON DELETE CASCADE 
ON UPDATE RESTRICT 
) ENGINE=INNODB; 

CREATE TABLE classement ( 
id_position INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
challenger INT UNSIGNED NOT NULL, 

CONSTRAINT cla_createur 
FOREIGN KEY (challenger) 
REFERENCES users (id_user) 
ON DELETE CASCADE 
ON UPDATE RESTRICT) ENGINE=INNODB;